# Generated by Django 2.1 on 2018-10-06 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('types', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GategiriesProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gategprod', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('menu_id', models.IntegerField()),
                ('parent_id', models.IntegerField()),
                ('parent_id_two', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PtoductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('disple', models.CharField(max_length=20)),
                ('des', models.CharField(max_length=20)),
                ('gat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_project.GategiriesProduct')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_project.Item')),
                ('propertys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_project.Attributes')),
            ],
        ),
    ]
