# Generated by Django 2.1 on 2018-11-06 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('decs', models.CharField(max_length=150)),
                ('material_body', models.CharField(max_length=25)),
                ('water_protection', models.CharField(max_length=25)),
                ('Dimensions', models.CharField(max_length=25)),
                ('weight', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=25)),
                ('screen_type', models.CharField(max_length=25)),
                ('screen_size', models.CharField(max_length=25)),
                ('screen_px', models.CharField(max_length=25)),
                ('gategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_project.Menus')),
            ],
        ),
    ]
