# Generated by Django 2.1 on 2018-11-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_project', '0002_productphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='productphone',
            name='prise',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productphone',
            name='decs',
            field=models.TextField(),
        ),
    ]
