# Generated by Django 2.1 on 2018-11-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_project', '0003_auto_20181106_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptoductitem',
            name='gat',
        ),
        migrations.RemoveField(
            model_name='value',
            name='item',
        ),
        migrations.RemoveField(
            model_name='value',
            name='propertys',
        ),
        migrations.DeleteModel(
            name='Attributes',
        ),
        migrations.DeleteModel(
            name='GategiriesProduct',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='PtoductItem',
        ),
        migrations.DeleteModel(
            name='Value',
        ),
    ]
