# Generated by Django 2.1 on 2018-11-14 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_project', '0005_attributes_gategiriesproduct_item_ptoductitem_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prise', models.IntegerField()),
                ('title', models.CharField(max_length=25)),
                ('decs', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='productphone',
            name='gategory',
        ),
        migrations.RemoveField(
            model_name='ptoductitem',
            name='gat',
        ),
        migrations.RemoveField(
            model_name='ptoductitem',
            name='value',
        ),
        migrations.RemoveField(
            model_name='value',
            name='item',
        ),
        migrations.RemoveField(
            model_name='value',
            name='propertys',
        ),
        migrations.RemoveField(
            model_name='menus',
            name='menu_id',
        ),
        migrations.RemoveField(
            model_name='menus',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='menus',
            name='parent_id_two',
        ),
        migrations.DeleteModel(
            name='Attributes',
        ),
        migrations.DeleteModel(
            name='GategiriesProduct',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ProductPhone',
        ),
        migrations.DeleteModel(
            name='PtoductItem',
        ),
        migrations.DeleteModel(
            name='Value',
        ),
        migrations.AddField(
            model_name='product',
            name='gategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_project.Menus'),
        ),
    ]
