# Generated by Django 2.1 on 2019-01-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_project', '0007_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
