# Generated by Django 2.1.7 on 2019-07-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_project', '0009_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AlterField(
            model_name='product',
            name='decs',
            field=models.TextField(verbose_name='decs'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gategory',
            field=models.ForeignKey(on_delete='gategory', to='first_project.Menus'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prise',
            field=models.IntegerField(verbose_name='prise'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=25, verbose_name='title'),
        ),
    ]
