# Generated by Django 2.1.7 on 2019-07-15 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_project', '0011_article_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='autor',
        ),
    ]
